FROM ghcr.io/graalvm/native-image-community:17-ol8 AS builder

ENV JAR_FILE=graal-vm-0.0.1-SNAPSHOT.jar
RUN mkdir /build
COPY build/libs/$JAR_FILE /build
WORKDIR /build

RUN rm -rf native \
 && mkdir -p native \
 && cd native \
 && jar -xvf ../$JAR_FILE \
# && native-image -H:Name=graal-vm @META-INF/native-image/argfile -cp .:BOOT-INF/classes:`find BOOT-INF/lib | tr '\n' ':'` \
 && native-image -H:Name=app-native -cp .:BOOT-INF/classes:`find BOOT-INF/lib | tr '\n' ':'` \
 && mv app-native ../

# Second stage: ubuntu jammy image
FROM ubuntu:jammy

WORKDIR /app

# Copy the native binary from the build stage
COPY --from=builder /build/app-native /app/spring-native

EXPOSE 8080

# Run the application
CMD ["/app/spring-native"]
